################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tflite/tensorflow/lite/micro/kernels/activations.cc \
../tflite/tensorflow/lite/micro/kernels/activations_common.cc \
../tflite/tensorflow/lite/micro/kernels/add_common.cc \
../tflite/tensorflow/lite/micro/kernels/add_n.cc \
../tflite/tensorflow/lite/micro/kernels/arg_min_max.cc \
../tflite/tensorflow/lite/micro/kernels/assign_variable.cc \
../tflite/tensorflow/lite/micro/kernels/batch_matmul.cc \
../tflite/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../tflite/tensorflow/lite/micro/kernels/broadcast_args.cc \
../tflite/tensorflow/lite/micro/kernels/broadcast_to.cc \
../tflite/tensorflow/lite/micro/kernels/call_once.cc \
../tflite/tensorflow/lite/micro/kernels/cast.cc \
../tflite/tensorflow/lite/micro/kernels/ceil.cc \
../tflite/tensorflow/lite/micro/kernels/circular_buffer.cc \
../tflite/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../tflite/tensorflow/lite/micro/kernels/comparisons.cc \
../tflite/tensorflow/lite/micro/kernels/concatenation.cc \
../tflite/tensorflow/lite/micro/kernels/conv_common.cc \
../tflite/tensorflow/lite/micro/kernels/cumsum.cc \
../tflite/tensorflow/lite/micro/kernels/depth_to_space.cc \
../tflite/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../tflite/tensorflow/lite/micro/kernels/dequantize.cc \
../tflite/tensorflow/lite/micro/kernels/dequantize_common.cc \
../tflite/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../tflite/tensorflow/lite/micro/kernels/div.cc \
../tflite/tensorflow/lite/micro/kernels/elementwise.cc \
../tflite/tensorflow/lite/micro/kernels/elu.cc \
../tflite/tensorflow/lite/micro/kernels/embedding_lookup.cc \
../tflite/tensorflow/lite/micro/kernels/ethosu.cc \
../tflite/tensorflow/lite/micro/kernels/exp.cc \
../tflite/tensorflow/lite/micro/kernels/expand_dims.cc \
../tflite/tensorflow/lite/micro/kernels/fill.cc \
../tflite/tensorflow/lite/micro/kernels/floor.cc \
../tflite/tensorflow/lite/micro/kernels/floor_div.cc \
../tflite/tensorflow/lite/micro/kernels/floor_mod.cc \
../tflite/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../tflite/tensorflow/lite/micro/kernels/gather.cc \
../tflite/tensorflow/lite/micro/kernels/gather_nd.cc \
../tflite/tensorflow/lite/micro/kernels/hard_swish.cc \
../tflite/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../tflite/tensorflow/lite/micro/kernels/if.cc \
../tflite/tensorflow/lite/micro/kernels/kernel_runner.cc \
../tflite/tensorflow/lite/micro/kernels/kernel_util.cc \
../tflite/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../tflite/tensorflow/lite/micro/kernels/l2norm.cc \
../tflite/tensorflow/lite/micro/kernels/leaky_relu.cc \
../tflite/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../tflite/tensorflow/lite/micro/kernels/log_softmax.cc \
../tflite/tensorflow/lite/micro/kernels/logical.cc \
../tflite/tensorflow/lite/micro/kernels/logical_common.cc \
../tflite/tensorflow/lite/micro/kernels/logistic.cc \
../tflite/tensorflow/lite/micro/kernels/logistic_common.cc \
../tflite/tensorflow/lite/micro/kernels/lstm_eval.cc \
../tflite/tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../tflite/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../tflite/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../tflite/tensorflow/lite/micro/kernels/mirror_pad.cc \
../tflite/tensorflow/lite/micro/kernels/mul_common.cc \
../tflite/tensorflow/lite/micro/kernels/neg.cc \
../tflite/tensorflow/lite/micro/kernels/pack.cc \
../tflite/tensorflow/lite/micro/kernels/pad.cc \
../tflite/tensorflow/lite/micro/kernels/pooling_common.cc \
../tflite/tensorflow/lite/micro/kernels/prelu.cc \
../tflite/tensorflow/lite/micro/kernels/prelu_common.cc \
../tflite/tensorflow/lite/micro/kernels/quantize.cc \
../tflite/tensorflow/lite/micro/kernels/quantize_common.cc \
../tflite/tensorflow/lite/micro/kernels/read_variable.cc \
../tflite/tensorflow/lite/micro/kernels/reduce.cc \
../tflite/tensorflow/lite/micro/kernels/reduce_common.cc \
../tflite/tensorflow/lite/micro/kernels/reshape.cc \
../tflite/tensorflow/lite/micro/kernels/reshape_common.cc \
../tflite/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../tflite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../tflite/tensorflow/lite/micro/kernels/round.cc \
../tflite/tensorflow/lite/micro/kernels/select.cc \
../tflite/tensorflow/lite/micro/kernels/shape.cc \
../tflite/tensorflow/lite/micro/kernels/slice.cc \
../tflite/tensorflow/lite/micro/kernels/softmax_common.cc \
../tflite/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../tflite/tensorflow/lite/micro/kernels/space_to_depth.cc \
../tflite/tensorflow/lite/micro/kernels/split.cc \
../tflite/tensorflow/lite/micro/kernels/split_v.cc \
../tflite/tensorflow/lite/micro/kernels/squared_difference.cc \
../tflite/tensorflow/lite/micro/kernels/squeeze.cc \
../tflite/tensorflow/lite/micro/kernels/strided_slice.cc \
../tflite/tensorflow/lite/micro/kernels/strided_slice_common.cc \
../tflite/tensorflow/lite/micro/kernels/sub.cc \
../tflite/tensorflow/lite/micro/kernels/sub_common.cc \
../tflite/tensorflow/lite/micro/kernels/svdf_common.cc \
../tflite/tensorflow/lite/micro/kernels/tanh.cc \
../tflite/tensorflow/lite/micro/kernels/transpose.cc \
../tflite/tensorflow/lite/micro/kernels/unpack.cc \
../tflite/tensorflow/lite/micro/kernels/var_handle.cc \
../tflite/tensorflow/lite/micro/kernels/while.cc \
../tflite/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./tflite/tensorflow/lite/micro/kernels/activations.d \
./tflite/tensorflow/lite/micro/kernels/activations_common.d \
./tflite/tensorflow/lite/micro/kernels/add_common.d \
./tflite/tensorflow/lite/micro/kernels/add_n.d \
./tflite/tensorflow/lite/micro/kernels/arg_min_max.d \
./tflite/tensorflow/lite/micro/kernels/assign_variable.d \
./tflite/tensorflow/lite/micro/kernels/batch_matmul.d \
./tflite/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./tflite/tensorflow/lite/micro/kernels/broadcast_args.d \
./tflite/tensorflow/lite/micro/kernels/broadcast_to.d \
./tflite/tensorflow/lite/micro/kernels/call_once.d \
./tflite/tensorflow/lite/micro/kernels/cast.d \
./tflite/tensorflow/lite/micro/kernels/ceil.d \
./tflite/tensorflow/lite/micro/kernels/circular_buffer.d \
./tflite/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./tflite/tensorflow/lite/micro/kernels/comparisons.d \
./tflite/tensorflow/lite/micro/kernels/concatenation.d \
./tflite/tensorflow/lite/micro/kernels/conv_common.d \
./tflite/tensorflow/lite/micro/kernels/cumsum.d \
./tflite/tensorflow/lite/micro/kernels/depth_to_space.d \
./tflite/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./tflite/tensorflow/lite/micro/kernels/dequantize.d \
./tflite/tensorflow/lite/micro/kernels/dequantize_common.d \
./tflite/tensorflow/lite/micro/kernels/detection_postprocess.d \
./tflite/tensorflow/lite/micro/kernels/div.d \
./tflite/tensorflow/lite/micro/kernels/elementwise.d \
./tflite/tensorflow/lite/micro/kernels/elu.d \
./tflite/tensorflow/lite/micro/kernels/embedding_lookup.d \
./tflite/tensorflow/lite/micro/kernels/ethosu.d \
./tflite/tensorflow/lite/micro/kernels/exp.d \
./tflite/tensorflow/lite/micro/kernels/expand_dims.d \
./tflite/tensorflow/lite/micro/kernels/fill.d \
./tflite/tensorflow/lite/micro/kernels/floor.d \
./tflite/tensorflow/lite/micro/kernels/floor_div.d \
./tflite/tensorflow/lite/micro/kernels/floor_mod.d \
./tflite/tensorflow/lite/micro/kernels/fully_connected_common.d \
./tflite/tensorflow/lite/micro/kernels/gather.d \
./tflite/tensorflow/lite/micro/kernels/gather_nd.d \
./tflite/tensorflow/lite/micro/kernels/hard_swish.d \
./tflite/tensorflow/lite/micro/kernels/hard_swish_common.d \
./tflite/tensorflow/lite/micro/kernels/if.d \
./tflite/tensorflow/lite/micro/kernels/kernel_runner.d \
./tflite/tensorflow/lite/micro/kernels/kernel_util.d \
./tflite/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./tflite/tensorflow/lite/micro/kernels/l2norm.d \
./tflite/tensorflow/lite/micro/kernels/leaky_relu.d \
./tflite/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./tflite/tensorflow/lite/micro/kernels/log_softmax.d \
./tflite/tensorflow/lite/micro/kernels/logical.d \
./tflite/tensorflow/lite/micro/kernels/logical_common.d \
./tflite/tensorflow/lite/micro/kernels/logistic.d \
./tflite/tensorflow/lite/micro/kernels/logistic_common.d \
./tflite/tensorflow/lite/micro/kernels/lstm_eval.d \
./tflite/tensorflow/lite/micro/kernels/lstm_eval_common.d \
./tflite/tensorflow/lite/micro/kernels/maximum_minimum.d \
./tflite/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./tflite/tensorflow/lite/micro/kernels/mirror_pad.d \
./tflite/tensorflow/lite/micro/kernels/mul_common.d \
./tflite/tensorflow/lite/micro/kernels/neg.d \
./tflite/tensorflow/lite/micro/kernels/pack.d \
./tflite/tensorflow/lite/micro/kernels/pad.d \
./tflite/tensorflow/lite/micro/kernels/pooling_common.d \
./tflite/tensorflow/lite/micro/kernels/prelu.d \
./tflite/tensorflow/lite/micro/kernels/prelu_common.d \
./tflite/tensorflow/lite/micro/kernels/quantize.d \
./tflite/tensorflow/lite/micro/kernels/quantize_common.d \
./tflite/tensorflow/lite/micro/kernels/read_variable.d \
./tflite/tensorflow/lite/micro/kernels/reduce.d \
./tflite/tensorflow/lite/micro/kernels/reduce_common.d \
./tflite/tensorflow/lite/micro/kernels/reshape.d \
./tflite/tensorflow/lite/micro/kernels/reshape_common.d \
./tflite/tensorflow/lite/micro/kernels/resize_bilinear.d \
./tflite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./tflite/tensorflow/lite/micro/kernels/round.d \
./tflite/tensorflow/lite/micro/kernels/select.d \
./tflite/tensorflow/lite/micro/kernels/shape.d \
./tflite/tensorflow/lite/micro/kernels/slice.d \
./tflite/tensorflow/lite/micro/kernels/softmax_common.d \
./tflite/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./tflite/tensorflow/lite/micro/kernels/space_to_depth.d \
./tflite/tensorflow/lite/micro/kernels/split.d \
./tflite/tensorflow/lite/micro/kernels/split_v.d \
./tflite/tensorflow/lite/micro/kernels/squared_difference.d \
./tflite/tensorflow/lite/micro/kernels/squeeze.d \
./tflite/tensorflow/lite/micro/kernels/strided_slice.d \
./tflite/tensorflow/lite/micro/kernels/strided_slice_common.d \
./tflite/tensorflow/lite/micro/kernels/sub.d \
./tflite/tensorflow/lite/micro/kernels/sub_common.d \
./tflite/tensorflow/lite/micro/kernels/svdf_common.d \
./tflite/tensorflow/lite/micro/kernels/tanh.d \
./tflite/tensorflow/lite/micro/kernels/transpose.d \
./tflite/tensorflow/lite/micro/kernels/unpack.d \
./tflite/tensorflow/lite/micro/kernels/var_handle.d \
./tflite/tensorflow/lite/micro/kernels/while.d \
./tflite/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./tflite/tensorflow/lite/micro/kernels/activations.o \
./tflite/tensorflow/lite/micro/kernels/activations_common.o \
./tflite/tensorflow/lite/micro/kernels/add_common.o \
./tflite/tensorflow/lite/micro/kernels/add_n.o \
./tflite/tensorflow/lite/micro/kernels/arg_min_max.o \
./tflite/tensorflow/lite/micro/kernels/assign_variable.o \
./tflite/tensorflow/lite/micro/kernels/batch_matmul.o \
./tflite/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./tflite/tensorflow/lite/micro/kernels/broadcast_args.o \
./tflite/tensorflow/lite/micro/kernels/broadcast_to.o \
./tflite/tensorflow/lite/micro/kernels/call_once.o \
./tflite/tensorflow/lite/micro/kernels/cast.o \
./tflite/tensorflow/lite/micro/kernels/ceil.o \
./tflite/tensorflow/lite/micro/kernels/circular_buffer.o \
./tflite/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./tflite/tensorflow/lite/micro/kernels/comparisons.o \
./tflite/tensorflow/lite/micro/kernels/concatenation.o \
./tflite/tensorflow/lite/micro/kernels/conv_common.o \
./tflite/tensorflow/lite/micro/kernels/cumsum.o \
./tflite/tensorflow/lite/micro/kernels/depth_to_space.o \
./tflite/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./tflite/tensorflow/lite/micro/kernels/dequantize.o \
./tflite/tensorflow/lite/micro/kernels/dequantize_common.o \
./tflite/tensorflow/lite/micro/kernels/detection_postprocess.o \
./tflite/tensorflow/lite/micro/kernels/div.o \
./tflite/tensorflow/lite/micro/kernels/elementwise.o \
./tflite/tensorflow/lite/micro/kernels/elu.o \
./tflite/tensorflow/lite/micro/kernels/embedding_lookup.o \
./tflite/tensorflow/lite/micro/kernels/ethosu.o \
./tflite/tensorflow/lite/micro/kernels/exp.o \
./tflite/tensorflow/lite/micro/kernels/expand_dims.o \
./tflite/tensorflow/lite/micro/kernels/fill.o \
./tflite/tensorflow/lite/micro/kernels/floor.o \
./tflite/tensorflow/lite/micro/kernels/floor_div.o \
./tflite/tensorflow/lite/micro/kernels/floor_mod.o \
./tflite/tensorflow/lite/micro/kernels/fully_connected_common.o \
./tflite/tensorflow/lite/micro/kernels/gather.o \
./tflite/tensorflow/lite/micro/kernels/gather_nd.o \
./tflite/tensorflow/lite/micro/kernels/hard_swish.o \
./tflite/tensorflow/lite/micro/kernels/hard_swish_common.o \
./tflite/tensorflow/lite/micro/kernels/if.o \
./tflite/tensorflow/lite/micro/kernels/kernel_runner.o \
./tflite/tensorflow/lite/micro/kernels/kernel_util.o \
./tflite/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./tflite/tensorflow/lite/micro/kernels/l2norm.o \
./tflite/tensorflow/lite/micro/kernels/leaky_relu.o \
./tflite/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./tflite/tensorflow/lite/micro/kernels/log_softmax.o \
./tflite/tensorflow/lite/micro/kernels/logical.o \
./tflite/tensorflow/lite/micro/kernels/logical_common.o \
./tflite/tensorflow/lite/micro/kernels/logistic.o \
./tflite/tensorflow/lite/micro/kernels/logistic_common.o \
./tflite/tensorflow/lite/micro/kernels/lstm_eval.o \
./tflite/tensorflow/lite/micro/kernels/lstm_eval_common.o \
./tflite/tensorflow/lite/micro/kernels/maximum_minimum.o \
./tflite/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./tflite/tensorflow/lite/micro/kernels/mirror_pad.o \
./tflite/tensorflow/lite/micro/kernels/mul_common.o \
./tflite/tensorflow/lite/micro/kernels/neg.o \
./tflite/tensorflow/lite/micro/kernels/pack.o \
./tflite/tensorflow/lite/micro/kernels/pad.o \
./tflite/tensorflow/lite/micro/kernels/pooling_common.o \
./tflite/tensorflow/lite/micro/kernels/prelu.o \
./tflite/tensorflow/lite/micro/kernels/prelu_common.o \
./tflite/tensorflow/lite/micro/kernels/quantize.o \
./tflite/tensorflow/lite/micro/kernels/quantize_common.o \
./tflite/tensorflow/lite/micro/kernels/read_variable.o \
./tflite/tensorflow/lite/micro/kernels/reduce.o \
./tflite/tensorflow/lite/micro/kernels/reduce_common.o \
./tflite/tensorflow/lite/micro/kernels/reshape.o \
./tflite/tensorflow/lite/micro/kernels/reshape_common.o \
./tflite/tensorflow/lite/micro/kernels/resize_bilinear.o \
./tflite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./tflite/tensorflow/lite/micro/kernels/round.o \
./tflite/tensorflow/lite/micro/kernels/select.o \
./tflite/tensorflow/lite/micro/kernels/shape.o \
./tflite/tensorflow/lite/micro/kernels/slice.o \
./tflite/tensorflow/lite/micro/kernels/softmax_common.o \
./tflite/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./tflite/tensorflow/lite/micro/kernels/space_to_depth.o \
./tflite/tensorflow/lite/micro/kernels/split.o \
./tflite/tensorflow/lite/micro/kernels/split_v.o \
./tflite/tensorflow/lite/micro/kernels/squared_difference.o \
./tflite/tensorflow/lite/micro/kernels/squeeze.o \
./tflite/tensorflow/lite/micro/kernels/strided_slice.o \
./tflite/tensorflow/lite/micro/kernels/strided_slice_common.o \
./tflite/tensorflow/lite/micro/kernels/sub.o \
./tflite/tensorflow/lite/micro/kernels/sub_common.o \
./tflite/tensorflow/lite/micro/kernels/svdf_common.o \
./tflite/tensorflow/lite/micro/kernels/tanh.o \
./tflite/tensorflow/lite/micro/kernels/transpose.o \
./tflite/tensorflow/lite/micro/kernels/unpack.o \
./tflite/tensorflow/lite/micro/kernels/var_handle.o \
./tflite/tensorflow/lite/micro/kernels/while.o \
./tflite/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
tflite/tensorflow/lite/micro/kernels/%.o tflite/tensorflow/lite/micro/kernels/%.su tflite/tensorflow/lite/micro/kernels/%.cyclo: ../tflite/tensorflow/lite/micro/kernels/%.cc tflite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G491xx -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/flatbuffers/include" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/gemmlowp" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/ruy" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/kissfft" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/signal" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/cmsis" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/cmsis_nn" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/cmsis_nn/Source/SVDFunctions" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/cmsis_nn/Source/SoftmaxFunctions" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/cmsis_nn/Source/ReshapeFunctions" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/cmsis_nn/Source/PoolingFunctions" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/third_party/cmsis_nn/Include" -I"C:/Users/giorg/Desktop/opt_micro_tflite/opt_micro_tflite/tflite/tensorflow/lite/micro/kernels/cmsis_nn" -Ofast -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -std=c++17 -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-tflite-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-tflite-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./tflite/tensorflow/lite/micro/kernels/activations.cyclo ./tflite/tensorflow/lite/micro/kernels/activations.d ./tflite/tensorflow/lite/micro/kernels/activations.o ./tflite/tensorflow/lite/micro/kernels/activations.su ./tflite/tensorflow/lite/micro/kernels/activations_common.cyclo ./tflite/tensorflow/lite/micro/kernels/activations_common.d ./tflite/tensorflow/lite/micro/kernels/activations_common.o ./tflite/tensorflow/lite/micro/kernels/activations_common.su ./tflite/tensorflow/lite/micro/kernels/add_common.cyclo ./tflite/tensorflow/lite/micro/kernels/add_common.d ./tflite/tensorflow/lite/micro/kernels/add_common.o ./tflite/tensorflow/lite/micro/kernels/add_common.su ./tflite/tensorflow/lite/micro/kernels/add_n.cyclo ./tflite/tensorflow/lite/micro/kernels/add_n.d ./tflite/tensorflow/lite/micro/kernels/add_n.o ./tflite/tensorflow/lite/micro/kernels/add_n.su ./tflite/tensorflow/lite/micro/kernels/arg_min_max.cyclo ./tflite/tensorflow/lite/micro/kernels/arg_min_max.d ./tflite/tensorflow/lite/micro/kernels/arg_min_max.o ./tflite/tensorflow/lite/micro/kernels/arg_min_max.su ./tflite/tensorflow/lite/micro/kernels/assign_variable.cyclo ./tflite/tensorflow/lite/micro/kernels/assign_variable.d ./tflite/tensorflow/lite/micro/kernels/assign_variable.o ./tflite/tensorflow/lite/micro/kernels/assign_variable.su ./tflite/tensorflow/lite/micro/kernels/batch_matmul.cyclo ./tflite/tensorflow/lite/micro/kernels/batch_matmul.d ./tflite/tensorflow/lite/micro/kernels/batch_matmul.o ./tflite/tensorflow/lite/micro/kernels/batch_matmul.su ./tflite/tensorflow/lite/micro/kernels/batch_to_space_nd.cyclo ./tflite/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./tflite/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./tflite/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./tflite/tensorflow/lite/micro/kernels/broadcast_args.cyclo ./tflite/tensorflow/lite/micro/kernels/broadcast_args.d ./tflite/tensorflow/lite/micro/kernels/broadcast_args.o ./tflite/tensorflow/lite/micro/kernels/broadcast_args.su ./tflite/tensorflow/lite/micro/kernels/broadcast_to.cyclo ./tflite/tensorflow/lite/micro/kernels/broadcast_to.d ./tflite/tensorflow/lite/micro/kernels/broadcast_to.o ./tflite/tensorflow/lite/micro/kernels/broadcast_to.su ./tflite/tensorflow/lite/micro/kernels/call_once.cyclo ./tflite/tensorflow/lite/micro/kernels/call_once.d ./tflite/tensorflow/lite/micro/kernels/call_once.o ./tflite/tensorflow/lite/micro/kernels/call_once.su ./tflite/tensorflow/lite/micro/kernels/cast.cyclo ./tflite/tensorflow/lite/micro/kernels/cast.d ./tflite/tensorflow/lite/micro/kernels/cast.o ./tflite/tensorflow/lite/micro/kernels/cast.su ./tflite/tensorflow/lite/micro/kernels/ceil.cyclo ./tflite/tensorflow/lite/micro/kernels/ceil.d ./tflite/tensorflow/lite/micro/kernels/ceil.o ./tflite/tensorflow/lite/micro/kernels/ceil.su ./tflite/tensorflow/lite/micro/kernels/circular_buffer.cyclo ./tflite/tensorflow/lite/micro/kernels/circular_buffer.d ./tflite/tensorflow/lite/micro/kernels/circular_buffer.o ./tflite/tensorflow/lite/micro/kernels/circular_buffer.su ./tflite/tensorflow/lite/micro/kernels/circular_buffer_common.cyclo ./tflite/tensorflow/lite/micro/kernels/circular_buffer_common.d ./tflite/tensorflow/lite/micro/kernels/circular_buffer_common.o ./tflite/tensorflow/lite/micro/kernels/circular_buffer_common.su ./tflite/tensorflow/lite/micro/kernels/comparisons.cyclo ./tflite/tensorflow/lite/micro/kernels/comparisons.d ./tflite/tensorflow/lite/micro/kernels/comparisons.o ./tflite/tensorflow/lite/micro/kernels/comparisons.su ./tflite/tensorflow/lite/micro/kernels/concatenation.cyclo ./tflite/tensorflow/lite/micro/kernels/concatenation.d ./tflite/tensorflow/lite/micro/kernels/concatenation.o ./tflite/tensorflow/lite/micro/kernels/concatenation.su ./tflite/tensorflow/lite/micro/kernels/conv_common.cyclo ./tflite/tensorflow/lite/micro/kernels/conv_common.d ./tflite/tensorflow/lite/micro/kernels/conv_common.o ./tflite/tensorflow/lite/micro/kernels/conv_common.su ./tflite/tensorflow/lite/micro/kernels/cumsum.cyclo ./tflite/tensorflow/lite/micro/kernels/cumsum.d ./tflite/tensorflow/lite/micro/kernels/cumsum.o ./tflite/tensorflow/lite/micro/kernels/cumsum.su ./tflite/tensorflow/lite/micro/kernels/depth_to_space.cyclo ./tflite/tensorflow/lite/micro/kernels/depth_to_space.d ./tflite/tensorflow/lite/micro/kernels/depth_to_space.o ./tflite/tensorflow/lite/micro/kernels/depth_to_space.su ./tflite/tensorflow/lite/micro/kernels/depthwise_conv_common.cyclo ./tflite/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./tflite/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./tflite/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./tflite/tensorflow/lite/micro/kernels/dequantize.cyclo ./tflite/tensorflow/lite/micro/kernels/dequantize.d ./tflite/tensorflow/lite/micro/kernels/dequantize.o ./tflite/tensorflow/lite/micro/kernels/dequantize.su ./tflite/tensorflow/lite/micro/kernels/dequantize_common.cyclo ./tflite/tensorflow/lite/micro/kernels/dequantize_common.d ./tflite/tensorflow/lite/micro/kernels/dequantize_common.o ./tflite/tensorflow/lite/micro/kernels/dequantize_common.su ./tflite/tensorflow/lite/micro/kernels/detection_postprocess.cyclo ./tflite/tensorflow/lite/micro/kernels/detection_postprocess.d ./tflite/tensorflow/lite/micro/kernels/detection_postprocess.o ./tflite/tensorflow/lite/micro/kernels/detection_postprocess.su ./tflite/tensorflow/lite/micro/kernels/div.cyclo ./tflite/tensorflow/lite/micro/kernels/div.d ./tflite/tensorflow/lite/micro/kernels/div.o ./tflite/tensorflow/lite/micro/kernels/div.su ./tflite/tensorflow/lite/micro/kernels/elementwise.cyclo ./tflite/tensorflow/lite/micro/kernels/elementwise.d ./tflite/tensorflow/lite/micro/kernels/elementwise.o ./tflite/tensorflow/lite/micro/kernels/elementwise.su ./tflite/tensorflow/lite/micro/kernels/elu.cyclo ./tflite/tensorflow/lite/micro/kernels/elu.d ./tflite/tensorflow/lite/micro/kernels/elu.o ./tflite/tensorflow/lite/micro/kernels/elu.su
	-$(RM) ./tflite/tensorflow/lite/micro/kernels/embedding_lookup.cyclo ./tflite/tensorflow/lite/micro/kernels/embedding_lookup.d ./tflite/tensorflow/lite/micro/kernels/embedding_lookup.o ./tflite/tensorflow/lite/micro/kernels/embedding_lookup.su ./tflite/tensorflow/lite/micro/kernels/ethosu.cyclo ./tflite/tensorflow/lite/micro/kernels/ethosu.d ./tflite/tensorflow/lite/micro/kernels/ethosu.o ./tflite/tensorflow/lite/micro/kernels/ethosu.su ./tflite/tensorflow/lite/micro/kernels/exp.cyclo ./tflite/tensorflow/lite/micro/kernels/exp.d ./tflite/tensorflow/lite/micro/kernels/exp.o ./tflite/tensorflow/lite/micro/kernels/exp.su ./tflite/tensorflow/lite/micro/kernels/expand_dims.cyclo ./tflite/tensorflow/lite/micro/kernels/expand_dims.d ./tflite/tensorflow/lite/micro/kernels/expand_dims.o ./tflite/tensorflow/lite/micro/kernels/expand_dims.su ./tflite/tensorflow/lite/micro/kernels/fill.cyclo ./tflite/tensorflow/lite/micro/kernels/fill.d ./tflite/tensorflow/lite/micro/kernels/fill.o ./tflite/tensorflow/lite/micro/kernels/fill.su ./tflite/tensorflow/lite/micro/kernels/floor.cyclo ./tflite/tensorflow/lite/micro/kernels/floor.d ./tflite/tensorflow/lite/micro/kernels/floor.o ./tflite/tensorflow/lite/micro/kernels/floor.su ./tflite/tensorflow/lite/micro/kernels/floor_div.cyclo ./tflite/tensorflow/lite/micro/kernels/floor_div.d ./tflite/tensorflow/lite/micro/kernels/floor_div.o ./tflite/tensorflow/lite/micro/kernels/floor_div.su ./tflite/tensorflow/lite/micro/kernels/floor_mod.cyclo ./tflite/tensorflow/lite/micro/kernels/floor_mod.d ./tflite/tensorflow/lite/micro/kernels/floor_mod.o ./tflite/tensorflow/lite/micro/kernels/floor_mod.su ./tflite/tensorflow/lite/micro/kernels/fully_connected_common.cyclo ./tflite/tensorflow/lite/micro/kernels/fully_connected_common.d ./tflite/tensorflow/lite/micro/kernels/fully_connected_common.o ./tflite/tensorflow/lite/micro/kernels/fully_connected_common.su ./tflite/tensorflow/lite/micro/kernels/gather.cyclo ./tflite/tensorflow/lite/micro/kernels/gather.d ./tflite/tensorflow/lite/micro/kernels/gather.o ./tflite/tensorflow/lite/micro/kernels/gather.su ./tflite/tensorflow/lite/micro/kernels/gather_nd.cyclo ./tflite/tensorflow/lite/micro/kernels/gather_nd.d ./tflite/tensorflow/lite/micro/kernels/gather_nd.o ./tflite/tensorflow/lite/micro/kernels/gather_nd.su ./tflite/tensorflow/lite/micro/kernels/hard_swish.cyclo ./tflite/tensorflow/lite/micro/kernels/hard_swish.d ./tflite/tensorflow/lite/micro/kernels/hard_swish.o ./tflite/tensorflow/lite/micro/kernels/hard_swish.su ./tflite/tensorflow/lite/micro/kernels/hard_swish_common.cyclo ./tflite/tensorflow/lite/micro/kernels/hard_swish_common.d ./tflite/tensorflow/lite/micro/kernels/hard_swish_common.o ./tflite/tensorflow/lite/micro/kernels/hard_swish_common.su ./tflite/tensorflow/lite/micro/kernels/if.cyclo ./tflite/tensorflow/lite/micro/kernels/if.d ./tflite/tensorflow/lite/micro/kernels/if.o ./tflite/tensorflow/lite/micro/kernels/if.su ./tflite/tensorflow/lite/micro/kernels/kernel_runner.cyclo ./tflite/tensorflow/lite/micro/kernels/kernel_runner.d ./tflite/tensorflow/lite/micro/kernels/kernel_runner.o ./tflite/tensorflow/lite/micro/kernels/kernel_runner.su ./tflite/tensorflow/lite/micro/kernels/kernel_util.cyclo ./tflite/tensorflow/lite/micro/kernels/kernel_util.d ./tflite/tensorflow/lite/micro/kernels/kernel_util.o ./tflite/tensorflow/lite/micro/kernels/kernel_util.su ./tflite/tensorflow/lite/micro/kernels/l2_pool_2d.cyclo ./tflite/tensorflow/lite/micro/kernels/l2_pool_2d.d ./tflite/tensorflow/lite/micro/kernels/l2_pool_2d.o ./tflite/tensorflow/lite/micro/kernels/l2_pool_2d.su ./tflite/tensorflow/lite/micro/kernels/l2norm.cyclo ./tflite/tensorflow/lite/micro/kernels/l2norm.d ./tflite/tensorflow/lite/micro/kernels/l2norm.o ./tflite/tensorflow/lite/micro/kernels/l2norm.su ./tflite/tensorflow/lite/micro/kernels/leaky_relu.cyclo ./tflite/tensorflow/lite/micro/kernels/leaky_relu.d ./tflite/tensorflow/lite/micro/kernels/leaky_relu.o ./tflite/tensorflow/lite/micro/kernels/leaky_relu.su ./tflite/tensorflow/lite/micro/kernels/leaky_relu_common.cyclo ./tflite/tensorflow/lite/micro/kernels/leaky_relu_common.d ./tflite/tensorflow/lite/micro/kernels/leaky_relu_common.o ./tflite/tensorflow/lite/micro/kernels/leaky_relu_common.su ./tflite/tensorflow/lite/micro/kernels/log_softmax.cyclo ./tflite/tensorflow/lite/micro/kernels/log_softmax.d ./tflite/tensorflow/lite/micro/kernels/log_softmax.o ./tflite/tensorflow/lite/micro/kernels/log_softmax.su ./tflite/tensorflow/lite/micro/kernels/logical.cyclo ./tflite/tensorflow/lite/micro/kernels/logical.d ./tflite/tensorflow/lite/micro/kernels/logical.o ./tflite/tensorflow/lite/micro/kernels/logical.su ./tflite/tensorflow/lite/micro/kernels/logical_common.cyclo ./tflite/tensorflow/lite/micro/kernels/logical_common.d ./tflite/tensorflow/lite/micro/kernels/logical_common.o ./tflite/tensorflow/lite/micro/kernels/logical_common.su ./tflite/tensorflow/lite/micro/kernels/logistic.cyclo ./tflite/tensorflow/lite/micro/kernels/logistic.d ./tflite/tensorflow/lite/micro/kernels/logistic.o ./tflite/tensorflow/lite/micro/kernels/logistic.su ./tflite/tensorflow/lite/micro/kernels/logistic_common.cyclo ./tflite/tensorflow/lite/micro/kernels/logistic_common.d ./tflite/tensorflow/lite/micro/kernels/logistic_common.o ./tflite/tensorflow/lite/micro/kernels/logistic_common.su ./tflite/tensorflow/lite/micro/kernels/lstm_eval.cyclo ./tflite/tensorflow/lite/micro/kernels/lstm_eval.d ./tflite/tensorflow/lite/micro/kernels/lstm_eval.o ./tflite/tensorflow/lite/micro/kernels/lstm_eval.su ./tflite/tensorflow/lite/micro/kernels/lstm_eval_common.cyclo ./tflite/tensorflow/lite/micro/kernels/lstm_eval_common.d ./tflite/tensorflow/lite/micro/kernels/lstm_eval_common.o ./tflite/tensorflow/lite/micro/kernels/lstm_eval_common.su ./tflite/tensorflow/lite/micro/kernels/maximum_minimum.cyclo ./tflite/tensorflow/lite/micro/kernels/maximum_minimum.d ./tflite/tensorflow/lite/micro/kernels/maximum_minimum.o
	-$(RM) ./tflite/tensorflow/lite/micro/kernels/maximum_minimum.su ./tflite/tensorflow/lite/micro/kernels/micro_tensor_utils.cyclo ./tflite/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./tflite/tensorflow/lite/micro/kernels/micro_tensor_utils.o ./tflite/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./tflite/tensorflow/lite/micro/kernels/mirror_pad.cyclo ./tflite/tensorflow/lite/micro/kernels/mirror_pad.d ./tflite/tensorflow/lite/micro/kernels/mirror_pad.o ./tflite/tensorflow/lite/micro/kernels/mirror_pad.su ./tflite/tensorflow/lite/micro/kernels/mul_common.cyclo ./tflite/tensorflow/lite/micro/kernels/mul_common.d ./tflite/tensorflow/lite/micro/kernels/mul_common.o ./tflite/tensorflow/lite/micro/kernels/mul_common.su ./tflite/tensorflow/lite/micro/kernels/neg.cyclo ./tflite/tensorflow/lite/micro/kernels/neg.d ./tflite/tensorflow/lite/micro/kernels/neg.o ./tflite/tensorflow/lite/micro/kernels/neg.su ./tflite/tensorflow/lite/micro/kernels/pack.cyclo ./tflite/tensorflow/lite/micro/kernels/pack.d ./tflite/tensorflow/lite/micro/kernels/pack.o ./tflite/tensorflow/lite/micro/kernels/pack.su ./tflite/tensorflow/lite/micro/kernels/pad.cyclo ./tflite/tensorflow/lite/micro/kernels/pad.d ./tflite/tensorflow/lite/micro/kernels/pad.o ./tflite/tensorflow/lite/micro/kernels/pad.su ./tflite/tensorflow/lite/micro/kernels/pooling_common.cyclo ./tflite/tensorflow/lite/micro/kernels/pooling_common.d ./tflite/tensorflow/lite/micro/kernels/pooling_common.o ./tflite/tensorflow/lite/micro/kernels/pooling_common.su ./tflite/tensorflow/lite/micro/kernels/prelu.cyclo ./tflite/tensorflow/lite/micro/kernels/prelu.d ./tflite/tensorflow/lite/micro/kernels/prelu.o ./tflite/tensorflow/lite/micro/kernels/prelu.su ./tflite/tensorflow/lite/micro/kernels/prelu_common.cyclo ./tflite/tensorflow/lite/micro/kernels/prelu_common.d ./tflite/tensorflow/lite/micro/kernels/prelu_common.o ./tflite/tensorflow/lite/micro/kernels/prelu_common.su ./tflite/tensorflow/lite/micro/kernels/quantize.cyclo ./tflite/tensorflow/lite/micro/kernels/quantize.d ./tflite/tensorflow/lite/micro/kernels/quantize.o ./tflite/tensorflow/lite/micro/kernels/quantize.su ./tflite/tensorflow/lite/micro/kernels/quantize_common.cyclo ./tflite/tensorflow/lite/micro/kernels/quantize_common.d ./tflite/tensorflow/lite/micro/kernels/quantize_common.o ./tflite/tensorflow/lite/micro/kernels/quantize_common.su ./tflite/tensorflow/lite/micro/kernels/read_variable.cyclo ./tflite/tensorflow/lite/micro/kernels/read_variable.d ./tflite/tensorflow/lite/micro/kernels/read_variable.o ./tflite/tensorflow/lite/micro/kernels/read_variable.su ./tflite/tensorflow/lite/micro/kernels/reduce.cyclo ./tflite/tensorflow/lite/micro/kernels/reduce.d ./tflite/tensorflow/lite/micro/kernels/reduce.o ./tflite/tensorflow/lite/micro/kernels/reduce.su ./tflite/tensorflow/lite/micro/kernels/reduce_common.cyclo ./tflite/tensorflow/lite/micro/kernels/reduce_common.d ./tflite/tensorflow/lite/micro/kernels/reduce_common.o ./tflite/tensorflow/lite/micro/kernels/reduce_common.su ./tflite/tensorflow/lite/micro/kernels/reshape.cyclo ./tflite/tensorflow/lite/micro/kernels/reshape.d ./tflite/tensorflow/lite/micro/kernels/reshape.o ./tflite/tensorflow/lite/micro/kernels/reshape.su ./tflite/tensorflow/lite/micro/kernels/reshape_common.cyclo ./tflite/tensorflow/lite/micro/kernels/reshape_common.d ./tflite/tensorflow/lite/micro/kernels/reshape_common.o ./tflite/tensorflow/lite/micro/kernels/reshape_common.su ./tflite/tensorflow/lite/micro/kernels/resize_bilinear.cyclo ./tflite/tensorflow/lite/micro/kernels/resize_bilinear.d ./tflite/tensorflow/lite/micro/kernels/resize_bilinear.o ./tflite/tensorflow/lite/micro/kernels/resize_bilinear.su ./tflite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cyclo ./tflite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./tflite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./tflite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./tflite/tensorflow/lite/micro/kernels/round.cyclo ./tflite/tensorflow/lite/micro/kernels/round.d ./tflite/tensorflow/lite/micro/kernels/round.o ./tflite/tensorflow/lite/micro/kernels/round.su ./tflite/tensorflow/lite/micro/kernels/select.cyclo ./tflite/tensorflow/lite/micro/kernels/select.d ./tflite/tensorflow/lite/micro/kernels/select.o ./tflite/tensorflow/lite/micro/kernels/select.su ./tflite/tensorflow/lite/micro/kernels/shape.cyclo ./tflite/tensorflow/lite/micro/kernels/shape.d ./tflite/tensorflow/lite/micro/kernels/shape.o ./tflite/tensorflow/lite/micro/kernels/shape.su ./tflite/tensorflow/lite/micro/kernels/slice.cyclo ./tflite/tensorflow/lite/micro/kernels/slice.d ./tflite/tensorflow/lite/micro/kernels/slice.o ./tflite/tensorflow/lite/micro/kernels/slice.su ./tflite/tensorflow/lite/micro/kernels/softmax_common.cyclo ./tflite/tensorflow/lite/micro/kernels/softmax_common.d ./tflite/tensorflow/lite/micro/kernels/softmax_common.o ./tflite/tensorflow/lite/micro/kernels/softmax_common.su ./tflite/tensorflow/lite/micro/kernels/space_to_batch_nd.cyclo ./tflite/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./tflite/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./tflite/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./tflite/tensorflow/lite/micro/kernels/space_to_depth.cyclo ./tflite/tensorflow/lite/micro/kernels/space_to_depth.d ./tflite/tensorflow/lite/micro/kernels/space_to_depth.o ./tflite/tensorflow/lite/micro/kernels/space_to_depth.su ./tflite/tensorflow/lite/micro/kernels/split.cyclo ./tflite/tensorflow/lite/micro/kernels/split.d ./tflite/tensorflow/lite/micro/kernels/split.o ./tflite/tensorflow/lite/micro/kernels/split.su ./tflite/tensorflow/lite/micro/kernels/split_v.cyclo ./tflite/tensorflow/lite/micro/kernels/split_v.d ./tflite/tensorflow/lite/micro/kernels/split_v.o ./tflite/tensorflow/lite/micro/kernels/split_v.su ./tflite/tensorflow/lite/micro/kernels/squared_difference.cyclo ./tflite/tensorflow/lite/micro/kernels/squared_difference.d
	-$(RM) ./tflite/tensorflow/lite/micro/kernels/squared_difference.o ./tflite/tensorflow/lite/micro/kernels/squared_difference.su ./tflite/tensorflow/lite/micro/kernels/squeeze.cyclo ./tflite/tensorflow/lite/micro/kernels/squeeze.d ./tflite/tensorflow/lite/micro/kernels/squeeze.o ./tflite/tensorflow/lite/micro/kernels/squeeze.su ./tflite/tensorflow/lite/micro/kernels/strided_slice.cyclo ./tflite/tensorflow/lite/micro/kernels/strided_slice.d ./tflite/tensorflow/lite/micro/kernels/strided_slice.o ./tflite/tensorflow/lite/micro/kernels/strided_slice.su ./tflite/tensorflow/lite/micro/kernels/strided_slice_common.cyclo ./tflite/tensorflow/lite/micro/kernels/strided_slice_common.d ./tflite/tensorflow/lite/micro/kernels/strided_slice_common.o ./tflite/tensorflow/lite/micro/kernels/strided_slice_common.su ./tflite/tensorflow/lite/micro/kernels/sub.cyclo ./tflite/tensorflow/lite/micro/kernels/sub.d ./tflite/tensorflow/lite/micro/kernels/sub.o ./tflite/tensorflow/lite/micro/kernels/sub.su ./tflite/tensorflow/lite/micro/kernels/sub_common.cyclo ./tflite/tensorflow/lite/micro/kernels/sub_common.d ./tflite/tensorflow/lite/micro/kernels/sub_common.o ./tflite/tensorflow/lite/micro/kernels/sub_common.su ./tflite/tensorflow/lite/micro/kernels/svdf_common.cyclo ./tflite/tensorflow/lite/micro/kernels/svdf_common.d ./tflite/tensorflow/lite/micro/kernels/svdf_common.o ./tflite/tensorflow/lite/micro/kernels/svdf_common.su ./tflite/tensorflow/lite/micro/kernels/tanh.cyclo ./tflite/tensorflow/lite/micro/kernels/tanh.d ./tflite/tensorflow/lite/micro/kernels/tanh.o ./tflite/tensorflow/lite/micro/kernels/tanh.su ./tflite/tensorflow/lite/micro/kernels/transpose.cyclo ./tflite/tensorflow/lite/micro/kernels/transpose.d ./tflite/tensorflow/lite/micro/kernels/transpose.o ./tflite/tensorflow/lite/micro/kernels/transpose.su ./tflite/tensorflow/lite/micro/kernels/unpack.cyclo ./tflite/tensorflow/lite/micro/kernels/unpack.d ./tflite/tensorflow/lite/micro/kernels/unpack.o ./tflite/tensorflow/lite/micro/kernels/unpack.su ./tflite/tensorflow/lite/micro/kernels/var_handle.cyclo ./tflite/tensorflow/lite/micro/kernels/var_handle.d ./tflite/tensorflow/lite/micro/kernels/var_handle.o ./tflite/tensorflow/lite/micro/kernels/var_handle.su ./tflite/tensorflow/lite/micro/kernels/while.cyclo ./tflite/tensorflow/lite/micro/kernels/while.d ./tflite/tensorflow/lite/micro/kernels/while.o ./tflite/tensorflow/lite/micro/kernels/while.su ./tflite/tensorflow/lite/micro/kernels/zeros_like.cyclo ./tflite/tensorflow/lite/micro/kernels/zeros_like.d ./tflite/tensorflow/lite/micro/kernels/zeros_like.o ./tflite/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-tflite-2f-tensorflow-2f-lite-2f-micro-2f-kernels

